// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fuen28TestQuestion.Models.EFModels;

public partial class MemberGrade
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int TitleId { get; set; }

    public int? Grade { get; set; }

    public DateTime TestTime { get; set; }

    public virtual Member Member { get; set; }

    public virtual Title Title { get; set; }
}