// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fuen28TestQuestion.Models.EFModels;

public partial class Title
{
    public int Id { get; set; }

    public string TitleName { get; set; }

    public virtual ICollection<MemberGrade> MemberGrades { get; set; } = new List<MemberGrade>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}